name = "yorushika-fan-site"
compatibility_date = "2026-07-26"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "twikoo"
database_id = "163732de-b424-462c-836f-17a00e020b5e"
