name = "yorushika-fan-site"
compatibility_date = "2026-07-26"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "yorushika-fan-site"
database_id = "f9e6f3b6-6984-40cf-afb9-2df7c184437a"
