// lib/discography.js - 夜鹿 (Yorushika) 全量作品与自白数据表
export const YORUSHIKA_DISCOGRAPHY = [
  // --- 核心 Mini / Full Albums ---
  { id: 1, name: '夏草が邪魔をする', type: 'Mini Album', date: '2017.06.28', tracks: '7首', cover: '/covers/1.jpg', quote: '「言葉に出来ないから、歌を歌うことにした」' },
  { id: 2, name: '負け犬にアンコールはいらない', type: 'Mini Album', date: '2018.05.09', tracks: '9首', cover: '/covers/2.jpg', quote: '「ただ君に晴れ。夏の匂いがした」' },
  { id: 3, name: '藍二乗', type: 'Single', date: '2018.12.27', tracks: '1首', cover: '/covers/3.jpg', quote: '「人生は人生のまま、藍色の空に消えていく」' },
  { id: 4, name: 'だから僕は音楽を辞めた', type: 'Full Album', date: '2019.04.10', tracks: '14首', cover: '/covers/4.jpg', quote: '「エルマ、君へ。僕の音楽をすべてあげる」' },
  { id: 5, name: '心に穴が空いた', type: 'Single', date: '2019.06.24', tracks: '1首', cover: '/covers/5.jpg', quote: '「音楽なんて要らなかった、君がいればよかった」' },
  { id: 6, name: 'エルマ', type: 'Full Album', date: '2019.08.28', tracks: '14首', cover: '/covers/6.jpg', quote: '「ただ歌声を待っている。日記に書いた言葉のように」' },
  { id: 7, name: '盗作', type: 'Full Album', date: '2020.07.29', tracks: '14首', cover: '/covers/7.jpg', quote: '「音楽の盗作をして生きていた。それが僕の全てだった」' },
  { id: 8, name: '創作', type: 'EP', date: '2021.01.27', tracks: '5首', cover: '/covers/8.jpg', quote: '「春の病。君が笑うなら何でもよかった」' },
  { id: 9, name: '幻燈', type: 'Artbook Album', date: '2023.04.05', tracks: '25首', cover: '/covers/9.jpg', quote: '「画集をめくるたび、音が聞こえる」' },

  // --- Singles & Digital Releases ---
  { id: 10, name: '言って。', type: 'Track', date: '2017.06.28', tracks: 'Single', cover: '/covers/10.jpg', quote: '「言って。あのね、私本当は分かってたの」' },
  { id: 11, name: '雲と幽霊', type: 'Track', date: '2017.06.28', tracks: 'Single', cover: '/covers/11.jpg', quote: '「夜の街を歩く。誰も僕に気づかない」' },
  { id: 12, name: 'カトレア', type: 'Track', date: '2017.06.28', tracks: 'Single', cover: '/covers/12.jpg', quote: '「白いカトレアが咲く部屋で」' },
  { id: 13, name: 'ヒッチコック', type: 'Track', date: '2018.05.09', tracks: 'Single', cover: '/covers/13.jpg', quote: '「先生、人生相談です。この先の人生はどうすればいいですか」' },
  { id: 14, name: '準透明少年', type: 'Track', date: '2018.03.09', tracks: 'Single', cover: '/covers/14.jpg', quote: '「僕の身体は半分透明だ」' },
  { id: 15, name: 'ただ君に晴れ', type: 'Track', date: '2018.05.09', tracks: 'Single', cover: '/covers/15.jpg', quote: '「追憶の夏、君の影を追う」' },
  { id: 16, name: 'パレード', type: 'Track', date: '2018.12.27', tracks: 'Single', cover: '/covers/16.jpg', quote: '「街を往くパレードの音」' },
  { id: 17, name: '八月、某、月明かり', type: 'Track', date: '2019.03.11', tracks: 'Single', cover: '/covers/17.jpg', quote: '「最低だ、最低だ。僕の青春は」' },
  { id: 18, name: '詩書きと男', type: 'Track', date: '2019.04.10', tracks: 'Single', cover: '/covers/18.jpg', quote: '「言葉を紡ぐだけの日々」' },
  { id: 19, name: '雨とカプチーノ', type: 'Track', date: '2019.08.01', tracks: 'Single', cover: '/covers/19.jpg', quote: '「冷めたカプチーノと雨の音」' },
  { id: 20, name: 'ノーチラス', type: 'Track', date: '2019.08.27', tracks: 'Single', cover: '/covers/20.jpg', quote: '「深海を泳ぐ潜水艇のように」' },
  { id: 21, name: '春ひさぎ', type: 'Single', date: '2020.06.03', tracks: 'Single', cover: '/covers/21.jpg', quote: '「商売商売、春を売る」' },
  { id: 22, name: '思想犯', type: 'Single', date: '2020.06.24', tracks: 'Single', cover: '/covers/22.jpg', quote: '「盗作の思想、僕の頭の中」' },
  { id: 23, name: '花に亡霊', type: 'Single', date: '2020.04.22', tracks: 'Single', cover: '/covers/23.jpg', quote: '「もう忘れてしまったかな。夏の匂いは」' },
  { id: 24, name: '風を食む', type: 'Single', date: '2020.10.07', tracks: 'Single', cover: '/covers/24.jpg', quote: '「空腹を抱えて風を食む」' },
  { id: 25, name: '嘘月', type: 'Single', date: '2021.01.27', tracks: 'Single', cover: '/covers/25.jpg', quote: '「嘘をついた月が綺麗だった」' },
  { id: 26, name: '強盗と花束', type: 'Single', date: '2021.01.27', tracks: 'Single', cover: '/covers/26.jpg', quote: '「花束を持って逃避行」' },
  { id: 27, name: '又三郎', type: 'Single', date: '2021.06.07', tracks: 'Single', cover: '/covers/27.jpg', quote: '「どっどど どどうど どどうど どどう」' },
  { id: 28, name: '老人と海', type: 'Single', date: '2021.08.18', tracks: 'Single', cover: '/covers/28.jpg', quote: '「波の音だけが聞こえる」' },
  { id: 29, name: '月に吠える', type: 'Single', date: '2021.10.06', tracks: 'Single', cover: '/covers/29.jpg', quote: '「夜空を見上げて吠える」' },
  { id: 30, name: 'ブレーメン', type: 'Single', date: '2022.07.04', tracks: 'Single', cover: '/covers/30.jpg', quote: '「僕らは死ぬまで音楽隊」' },
  { id: 31, name: '左右盲', type: 'Single', date: '2022.07.25', tracks: 'Single', cover: '/covers/31.jpg', quote: '「右と左の区別もつかないまま」' },
  { id: 32, name: 'チノカテ', type: 'Single', date: '2022.08.29', tracks: 'Single', cover: '/covers/32.jpg', quote: '「地の糧。言葉を味わう」' },
  { id: 33, name: 'アルジャーノン', type: 'Single', date: '2023.01.26', tracks: 'Single', cover: '/covers/33.jpg', quote: '「ゆっくりと変わっていく」' },
  { id: 34, name: '斜陽', type: 'Single', date: '2023.05.08', tracks: 'Single', cover: '/covers/34.jpg', quote: '「夕日があまりに綺麗だから」' },
  { id: 35, name: '都落ち', type: 'Single', date: '2023.02.15', tracks: 'Single', cover: '/covers/35.jpg', quote: '「遠く離れた街へ」' },
  { id: 36, name: '第一夜', type: 'Single', date: '2023.04.05', tracks: 'Single', cover: '/covers/36.jpg', quote: '「こんな夢を見た」' },
  { id: 37, name: '月光浴', type: 'Single', date: '2023.10.13', tracks: 'Single', cover: '/covers/37.jpg', quote: '「静かな月光の下で」' },
  { id: 38, name: '晴る', type: 'Single', date: '2024.01.05', tracks: 'Single', cover: '/covers/38.jpg', quote: '「晴れ渡る空を見上げて」' },
  { id: 39, name: 'ルバート', type: 'Single', date: '2024.03.01', tracks: 'Single', cover: '/covers/39.jpg', quote: '「自由なテンポで奏でる」' },
  { id: 40, name: '忘れてください', type: 'Single', date: '2024.07.12', tracks: 'Single', cover: '/covers/40.jpg', quote: '「僕のことも、歌のことも」' },
  { id: 41, name: 'アポリア', type: 'Single', date: '2024.10.02', tracks: 'Single', cover: '/covers/41.jpg', quote: '「思考の行き詰まりの先へ」' },
  { id: 42, name: '太陽', type: 'Single', date: '2024.11.20', tracks: 'Single', cover: '/covers/42.jpg', quote: '「眩しい光の中で」' },
  { id: 43, name: '火種', type: 'Single', date: '2025.01.10', tracks: 'Single', cover: '/covers/43.jpg', quote: '「静かに燃える火種」' },
  { id: 44, name: 'へうげもの', type: 'Single', date: '2025.03.05', tracks: 'Single', cover: '/covers/44.jpg', quote: '「歪んだ美しさ」' },
  { id: 45, name: '修道女', type: 'Single', date: '2025.05.15', tracks: 'Single', cover: '/covers/45.jpg', quote: '「祈りの声」' },
  { id: 46, name: '音楽の盗作', type: 'Special', date: '2025.08.01', tracks: 'Album', cover: '/covers/46.jpg', quote: '「音楽を愛した、盗作の物語」' },
];
